name: .NET Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./twosum/twosum.csproj

    - name: Build
      run: dotnet build ./twosum/twosum.csproj --no-restore

    - name: Test
      run: dotnet test ./twosum/twosum.csproj --no-build --verbosity normal
